name: home_automation
description: An app to monitor and control Fan in the Home.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^5.5.0
  cupertino_icons: ^1.0.2
  provider: ^6.0.2
  ## shared preferences
  shared_preferences:
  ## MQTT client
  mqtt_client:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
